apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: simple-info-daemonset
  labels:
    app: simple-info-daemonset
spec:
  selector:
    matchLabels:
      app: simple-info-daemonset
  template:
    metadata:
      labels:
        app: simple-info-daemonset
    spec:
      containers:
      - name: simple-alpine
        image: alpine:3.14
        command: ["/bin/sh", "-c"]
        args:
          - |
            while true; do
              echo "Node: $(hostname)";
              echo "Pod Name: ${POD_NAME}";
              echo "Namespace: ${POD_NAMESPACE}";
              echo "Node Name: ${NODE_NAME}";
              echo "Sleeping for 30 seconds...";
              sleep 30;
            done;
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
