apiVersion: v1
kind: LimitRange
metadata:
  name: vote-limits
  namespace: vote
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: "100m"
        memory: "128Mi"
      default:
        cpu: "200m"
        memory: "256Mi"